name: Deploy Static Site

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Assuming your HTML, CSS, and JS files are in the root directory
